version: "3"

volumes:
  database-data:
  pgadmin-data:
  mongo-data:

networks:
  core:
    external: false

services:
  core:
    container_name: sanny-io-core
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    command: sleep infinity
    ports:
      - 3000:3000
    networks:
      - core
    depends_on:
      - database
      - mongo
    volumes:
      - .:/workspace:cached
    links:
      - database
  database:
    container_name: sanny-io-database
    image: postgres:14
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - core
    ports:
      - 5432:5432
  mongo:
    container_name: sanny-io-mongo
    image: mongo
    restart: always
    networks:
      - core
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: payload
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  pgadmin:
    image: dpage/pgadmin4
    container_name: sanny-io-pgadmin
    restart: always
    networks:
      - core
    depends_on:
      - database
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: sannysherief@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin